#!/bin/bash
read -p "Enter your text:" answer
read -p "Select background color:" backg
if [ $backg = "blue" ];then
   tput setab 4  
   clear         
elif [ $backg = "pink" ];then
	tput setab 5
	clear
elif [ $backg = "yellow" ];then
	tput setab 3
	clear
elif [ $backg = "red" ];then
	tput setab 9
	clear
elif [ $backg = "green" ];then
	tput setab 10
	clear
elif [ $backg = "aqua" ];then
	tput setab 6
	clear
fi
   cowsay -f tux "$answer"
sleep 999999
tput sgr0

