#!/bin/bash

if [ "$1" == "-l" ];then
	echo "Available color schemes:"
	echo "pink"
	echo "yellow"
	echo "red"
	echo "green"
	echo "aqua"
	echo "black"
	exit 1
fi

read -p "Enter your text:" answer
read -p "Select background color:" backg
read -p "Select text color:" foreg
if [ $backg = "blue" ];then
   tput setab 4  
   clear         
elif [ $backg = "pink" ];then
	tput setab 5
	clear
elif [ $backg = "yellow" ];then
	tput setab 3
	clear
elif [ $backg = "red" ];then
	tput setab 9
	clear
elif [ $backg = "green" ];then
	tput setab 10
	clear
elif [ $backg = "aqua" ];then
	tput setab 6
	clear
elif [ $backg = "black" ];then
	tput setab 0
	clear
else
	echo "Unsupported color scheme, look at bluetux -l"
	exit 1
fi 
	clear
	if [ $foreg = "red" ];then
		tput setaf 1
	elif [ $foreg = "green" ];then
		tput setaf 2
	elif [ $foreg = "yellow" ];then
		tput setaf 3
	elif [ $foreg = "blue" ];then
		tput setaf 4
	elif [ $foreg = "pink" ];then
		tput setaf 5
	elif [ $foreg = "aqua" ];then
		tput setaf 6
	elif [ $foreg = "white" ];then
		tput setaf 7
	elif [ $foreg = "black" ];then
		tput setaf 8
else
	echo "Unsupported color scheme, look at bluetux -l"
	exit 1
fi
   cowsay -f tux "$answer"
read -p " " pause
if [ $pause = "exit" ];then
tput sgr0
clear
exit 1
fi

